// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iejbifkpqayzqennpwuf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImllamJpZmtwcWF5enFlbm5wd3VmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MDgyODAsImV4cCI6MjA2Mjk4NDI4MH0.gnyWn8gxGvDaS4cY9ort1bBhPwEWD3lU9Eu6dt60IUs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);