// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hdeavqaoikojhlvvidtm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkZWF2cWFvaWtvamhsdnZpZHRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI1OTE1NDUsImV4cCI6MjA4ODE2NzU0NX0.nxQbQ3xoWYEC9UShwqN7V5gCyMVK52E8X-xFdhoe_Is";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});